#
# Production config
#
SCHEDULED_TASKS: True
CPU_TEMPERATURE_RECORD_INTERVAL: 10
CPU_PERCENTAGE_RECORD_INTERVAL: 10
MEMORY_PERCENTAGE_RECORD_INTERVAL: 10
RECORD_DELETE_INTERVAL: 86400
DELETE_RECORDS_OLDER_THAN: 2592000

LOGGING_LEVEL: INFO
DATABASE_URI: "sqlite:///db.sqlite3"