scheduled_tasks:
  # Enable/disable automated data recording tasks that run on a schedule
  enabled: True
  # Intervals (in seconds) for data recording/deleting tasks
  intervals:
    cpu_temperature: 10
    cpu_percentage: 10
    memory_percentage: 10
    deletion: 86400
  # Configuration for record deletion task
  deletion:
    # Enable/disable old record deletion
    enabled: True
    # Duration (in seconds) specifying records older than which will be deleted
    delete_older_than: 2592000

logging:
  level: INFO

database:
  uri: "sqlite:////data/db.sqlite3"