SCHEDULED_TASKS: False
CPU_TEMPERATURE_RECORD_INTERVAL: 0
CPU_PERCENTAGE_RECORD_INTERVAL: 0
MEMORY_PERCENTAGE_RECORD_INTERVAL: 0
RECORD_DELETE_INTERVAL: 0
DELETE_RECORDS_OLDER_THAN: 0

TESTING: True
LOGGING_LEVEL: ERROR
DATABASE_URI: "sqlite:///:memory:"